const productos = [{
        id: 1,
        foto: "./assets/imagenes/adidas1.jpg",
        nombre: "UltimaShow",
        precio: 3675,
        sexo: "hombre",
    },
    {
        id: 2,
        foto: "./assets/imagenes/adidas2.jpg",
        nombre: "Duramo 10",
        precio: 5900,
        sexo: "mujer",
    },
    {
        id: 3,
        foto: "./assets/imagenes/adidas3.jpg",
        nombre: "Duramo Protect",
        precio: 4250,
        sexo: "hombre",
    },
    {
        id: 4,
        foto: "./assets/imagenes/adidas4.jpg",
        nombre: "Duramo 9",
        precio: 3900,
        sexo: "mujer",
    },
    {
        id: 5,
        foto: "./assets/imagenes/adidas5.jpg",
        nombre: "EQ21 Run",
        precio: 3650,
        sexo: "mujer",
    },
    {
        id: 6,
        foto: "./assets/imagenes/adidas6.jpg",
        nombre: "X9000L2 Legend",
        precio: 4190,
        sexo: "hombre",
    },
    {
        id: 7,
        foto: "./assets/imagenes/adidas7.jpg",
        nombre: "Galaxy 6",
        precio: 4700,
        sexo: "mujer",
    },
    {
        id: 8,
        foto: "./assets/imagenes/sketcher1.jpg",
        nombre: "Go Run Razor 3",
        precio: 6999,
        sexo: "hombre",
    },
    {
        id: 9,
        foto: "./assets/imagenes/sketcher2.jpg",
        nombre: "Go Men Runing",
        precio: 6300,
        sexo: "mujer",
    },
    {
        id: 10,
        foto: "./assets/imagenes/sketcher3.jpg",
        nombre: "Go Run 7",
        precio: 5700,
        sexo: "mujer",
    },
    {
        id: 11,
        foto: "./assets/imagenes/sketcher4.jpg",
        nombre: "Go Run 8",
        precio: 6100,
        sexo: "hombre",
    },
    {
        id: 12,
        foto: "./assets/imagenes/sketcher5.jpg",
        nombre: "Go Run 4",
        precio: 3900,
        sexo: "mujer",
    },
    {
        id: 13,
        foto: "./assets/imagenes/sketcher6.jpg",
        nombre: "Go Run Balance 2",
        precio: 6500,
        sexo: "hombre",
    },
    {
        id: 14,
        foto: "./assets/imagenes/sketcher7.jpg",
        nombre: "Horizon Vanish 2",
        precio: 5600,
        sexo: "mujer",
    },
];