const productos = [
    { id: 1, foto: "./assets/imagenes/adidas1.jpg", nombre: "UltimaShow", precio: 3675, genero: "hombre", actividad: "running"},
    { id: 2, foto: "./assets/imagenes/adidas2.jpg", nombre: "Duramo 10", precio: 5900, genero: "mujer", actividad: "training"},
    { id: 3, foto: "./assets/imagenes/adidas3.jpg", nombre: "Duramo 6", precio: 4250, genero: "hombre", actividad: "running"},
    { id: 4, foto: "./assets/imagenes/adidas4.jpg", nombre: "Duramo 9", precio: 3900, genero: "unisex", actividad: "training"},
    { id: 5, foto: "./assets/imagenes/adidas5.jpg", nombre: "EQ21 Run", precio: 3650, genero: "mujer", actividad: "running"},
    { id: 6, foto: "./assets/imagenes/adidas6.jpg", nombre: "X90 Legend", precio: 4190, genero: "hombre", actividad: "training"},
    { id: 7, foto: "./assets/imagenes/adidas7.jpg", nombre: "Galaxy 6", precio: 4700, genero: "mujer", actividad: "running"},
    { id: 8, foto: "./assets/imagenes/sketcher1.jpg", nombre: "Go Run 3", precio: 6999, genero: "hombre", actividad: "training"},
    { id: 9, foto: "./assets/imagenes/sketcher2.jpg", nombre: "Go  running", precio: 6300, genero: "mujer", actividad: "running"},
    { id: 10, foto: "./assets/imagenes/sketcher3.jpg", nombre: "Go Run 7", precio: 5700, genero: "unisex", actividad: "training"},
    { id: 11, foto: "./assets/imagenes/sketcher4.jpg", nombre: "Go Run 8", precio: 6100, genero: "hombre", actividad: "running"},
    { id: 12, foto: "./assets/imagenes/sketcher5.jpg", nombre: "Go Run 4", precio: 3900, genero: "mujer", actividad: "training"},
    { id: 13, foto: "./assets/imagenes/sketcher6.jpg", nombre: "Go Run 2", precio: 6500, genero: "hombre", actividad: "running"},
    { id: 14, foto: "./assets/imagenes/sketcher7.jpg", nombre: "Horizon 2", precio: 5600, genero: "mujer", actividad: "training"},
    { id: 15, foto: "./assets/imagenes/nb1.jpg", nombre: "New Balance V1", precio: 2400, genero: "mujer", actividad: "training"},
    { id: 16, foto: "./assets/imagenes/nb2.jpg", nombre: "New Balance V2", precio: 2900, genero: "unisex", actividad: "running"},
    { id: 17, foto: "./assets/imagenes/nb3.jpg", nombre: "New Balance V3", precio: 2800, genero: "mujer", actividad: "training"},
    { id: 18, foto: "./assets/imagenes/nb4.jpg", nombre: "New Balance V4", precio: 3100, genero: "hombre", actividad: "running"},
    { id: 19, foto: "./assets/imagenes/nb5.jpg", nombre: "New Balance V5", precio: 3380, genero: "mujer", actividad: "training"},
    { id: 20, foto: "./assets/imagenes/nb6.jpg", nombre: "New Balance V6", precio: 3700, genero: "unisex", actividad: "training"},
    { id: 21, foto: "./assets/imagenes/nb7.jpg", nombre: "New Balance V7", precio: 3400, genero: "hombre", actividad: "running"},
    { id: 22, foto: "./assets/imagenes/nb8.jpg", nombre: "New Balance V8", precio: 3690, genero: "unisex", actividad: "training"},
    { id: 23, foto: "./assets/imagenes/nb9.jpg", nombre: "New Balance V9", precio: 3890, genero: "unisex", actividad: "running"},
    { id: 24, foto: "./assets/imagenes/nb10.jpg", nombre: "New Balance V10", precio: 3900, genero: "mujer", actividad: "training"},
];